### ISSUE TITLE
why are we tracking the composer.lock?

### ISSUE THREAD

**Issue by cordoval** [igorw/stack-oauth#3]

**Comment by igorw** [comment]
Because that is the point of composer.lock. You're supposed to commit it into version control. See also: Composer docs.

**Comment by cordoval** [comment]
but thought this is a library, maybe when we move to stable we can get rid of this
until then is ok i guess :baby:

**Comment by igorw** [comment]
It doesn't affect anyone installing the library. It's just to track which versions are actually being developed against.

**Comment by cordoval** [comment]
right, k :)
